server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_security
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  name: IAM-SERVICE
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 120000
      refresh-token:
        expiration: 300000